/**
 * This file is part of the Gribbit Web Framework.
 * 
 *     https://github.com/lukehutch/gribbit
 * 
 * @author Luke Hutchison
 * 
 * --
 * 
 * @license Apache 2.0 
 * 
 * Copyright 2015 Luke Hutchison
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gribbit.http.request.handler;

import gribbit.http.request.Request;
import gribbit.http.response.GeneralResponse;
import gribbit.http.response.exception.ResponseException;

public interface HttpRequestHandler {
    /**
     * Handle the given request, generating a response.
     * 
     * @param request
     *            The request.
     * @return The response generated by the request, if this handler was able to handle the request, otherwise
     *         should return null, and the request will be passed on to the next handler.
     * @throws ResponseException
     */
    public GeneralResponse handle(Request request) throws ResponseException;
}
